# Generated by Django 5.0.2 on 2024-02-19 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TsDeportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('equipacion_principal', models.CharField(max_length=100)),
                ('equipacion_suplente', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='Instalaciones',
            fields=[
                ('id_instalacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('iluminacion', models.BooleanField(default=False, verbose_name='Iluminacion')),
                ('cubierta', models.BooleanField(default=False, verbose_name='Cubierta')),
            ],
            options={
                'verbose_name': 'Instalacion',
                'verbose_name_plural': 'Instalaciones',
                'db_table': 'instalaciones',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id_jugador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(blank=True, max_length=20, null=True)),
                ('dorsal', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('peso', models.IntegerField()),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id_partido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('puntos_local', models.IntegerField(null=True)),
                ('puntos_visitante', models.IntegerField(null=True)),
                ('observaciones', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.AlterField(
            model_name='deportes',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='id_deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TsDeportes.deportes'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='id_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TsDeportes.equipo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='id_deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TsDeportes.deportes'),
        ),
        migrations.AddField(
            model_name='partido',
            name='id_instalacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TsDeportes.instalaciones'),
        ),
        migrations.AddField(
            model_name='partido',
            name='id_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_partidos', to='TsDeportes.equipo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='id_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante_partidos', to='TsDeportes.equipo'),
        ),
    ]
